environment: "local"
logger:
  minLevel: "INFO"
bot:
  initTimeout: 5s
  allowedUserID: 140302304
httpServer:
  addr: ":2000"
gitRepository:
  url: "git@github.com:protomorphine/notes.git"
  path: "/home/drzaytsev/notes/"
  saveTo: "bot-notes"
  branch: "tg-notes"
  bufSize: 5
  updateDuration: 1m
  committer:
    name: "tg-notes-bot"
