environment: "local"
logger:
  minLevel: "INFO"
bot:
  webHookURL: "https://bmgspmt3-2000.euw.devtunnels.ms"
  initTimeout: 5s
  allowedUserID: 140302304
httpServer:
  addr: ":2000"
gitRepository:
  url: "git@github.com:protomorphine/notes.git"
  path: "/home/drzaytsev/notes/"
  keyPath: "/home/drzaytsev/.ssh/id_ed25519"
  saveTo: "bot-notes"
  branch: "tg-notes"
  committer:
    name: "tg-notes-bot"
